aliases: []
creation_timestamp: 1753811601144
current_stage: None
description: null
last_updated_timestamp: 1753811601144
name: sentiment_analysis_pipeline
run_id: 2a6d6fa86c294092b36eae196d3801c1
run_link: null
source: file:///content/IA/mlflow/613269214425265126/2a6d6fa86c294092b36eae196d3801c1/artifacts/sentiment_analysis
status: READY
status_message: null
storage_location: file:///content/IA/mlflow/613269214425265126/2a6d6fa86c294092b36eae196d3801c1/artifacts/sentiment_analysis
user_id: null
version: 6
