aliases: []
creation_timestamp: 1742048767342
current_stage: None
description: null
last_updated_timestamp: 1742048767342
name: sentiment_analysis_pipeline
run_id: d54beb66b2744eb599f6deb056fde10b
run_link: null
source: file:///content/Practica/mlflow/904312190776831578/d54beb66b2744eb599f6deb056fde10b/artifacts/sentiment_analysis
status: READY
status_message: null
storage_location: file:///content/Practica/mlflow/904312190776831578/d54beb66b2744eb599f6deb056fde10b/artifacts/sentiment_analysis
user_id: null
version: 2
